# Generated by Django 4.2.21 on 2025-05-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Текст комментария"),
        ),
    ]
